fft_length : 131072
stream_number : 2
input_type_flag : 0

begin_channel : 32768 #min value is 1(not support 0)
compress_channel_num : 32768
window_size : 2048
batch_buffer_size : 4096
step : 4

write_head : 0
print_memory : 0 
write_data : 1

tsamp : 8e-10
machine_id_in : 0
telescope_id_in : 0

#set to 0 to let program auto select a number
thread_num : 0

#cannot be empty
#if output_name and file name stream are set to relative path , they are considered relative to current shell path
output_name : /tmp/output_2_32768_0.99.fil
source_name_in : rawdata

#the unit of phase_shift is (PI*rad)
#the value of weight should be normalized
stream :
    - file : /ssd/liuzh/data/B0950/B0950+08_tracking_0001_A.dat
      phase_shift : 0.0
      weight : 0.5

    - file : /ssd/liuzh/data/B0950/B0950+08_tracking_0001_A.dat
      phase_shift : 0.99
      weight : 0.5
